#!/bin/bash

#/*****************************************************************
# SCRIPT: mysql_prep.sh
# AUTHOR: Pravin Regismond
# DATE: 2024-04-11
# DESCRIPTION: Exercise 1 - Prepare the lab environment
#              - Start MySQL server on the IBM Skills Network Labs
#              - Create a database named 'tolldata'
#              - Create a table named 'livetolldata' with the
#                schema to store the data generated by the traffic
#                simulator
#              - Install the python module 'kafka-python'
#              - Install the python module 'mysql-connector-python'
#
#******************************************************************
# AUDIT TRAIL START                               INIT  DATE
# ----------------------------------------------  ----- -----------
# 1. Initial version                              PR    2024-04-11
#
# AUDIT TRAIL END
#******************************************************************/

# Start MySQL server
start_mysql

# Connect to mysql server
mysql --host=127.0.0.1 --port=3306 --user=root --password=${MYSQL_PASSWORD} << EOF
-- Create a database named tolldata
system echo 'Creating tolldata database';
create database tolldata;

-- Create a table named livetolldata with the schema to store the data generated by the traffic simulator
system echo 'Creating livetolldata table';
use tolldata;
create table livetolldata(timestamp datetime,vehicle_id int,vehicle_type char(15),toll_plaza_id smallint);
exit
EOF

# Install python module kafka-python using pip command
python3 -m pip install kafka-python

# Install python module mysql-connector-python using pip command
python3 -m pip install mysql-connector-python==8.0.31
